/*
SQLyog Enterprise - MySQL GUI v5.25
Host - 5.5.41-log : Database - unorganised
*********************************************************************
Server version : 5.5.41-log
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

create database if not exists `unorganised`;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*Table structure for table `city` */

CREATE TABLE `city` (
  `city_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `state_id` bigint(20) DEFAULT NULL,
  `city_name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`city_id`)
) ENGINE=InnoDB AUTO_INCREMENT=272 DEFAULT CHARSET=utf8;

/*Data for the table `city` */

insert  into `city`(`city_id`,`state_id`,`city_name`) values (1,1,'Bamboo Flat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (2,1,'Garacherama');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (3,1,'Port Blair');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (4,1,'Prothrapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (5,2,'Visakhapatnam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (6,2,'Vijayawada');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (7,2,'Guntur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (8,2,'Nellore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (9,2,'Kurnool');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (10,2,'Rajahmundry');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (11,2,'Tirupati');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (12,2,'Kakinada');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (13,2,'Kadapa');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (14,2,'Anantapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (15,3,'Aalo');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (16,3,'Itanagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (17,3,'Naharlagun');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (18,3,'Pasighat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (19,4,'Guwahati');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (20,4,'Silchar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (21,4,'Dibrugarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (22,4,'Jorhat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (23,4,'Nagaon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (24,4,'Tinsukia');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (25,4,'Tezpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (26,4,'Bongaigaon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (27,4,'Karimganj');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (28,4,'Dhubri');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (29,4,'Diphu');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (30,5,'Patna');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (31,5,'Gaya');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (32,5,'Bhagalpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (33,5,'Muzaffarpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (34,5,'Purnia');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (35,5,'Darbhanga');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (36,5,'Bihar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (37,5,'Ara');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (38,5,'Begusarai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (39,5,'Katihar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (40,6,'Chandigarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (41,7,'Raipur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (42,7,'Bhilai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (43,7,'Bilaspur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (44,7,'Korba');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (45,7,'Raj Nandgaon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (46,7,'Raigarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (47,7,'Jagdalpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (48,7,'Ambikapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (49,7,'Dhamtari');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (50,8,'Dadra');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (51,8,'Masat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (52,8,'Naroli');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (53,8,'Samarvarni');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (54,8,'Silvassa');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (55,9,'Dadhel');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (56,9,'Daman');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (57,9,'Diu');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (58,9,'Kachigam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (59,10,'Delhi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (60,10,'Jaffarpur Kalan');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (61,10,'Qutabgarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (62,10,'Ujwa');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (63,11,'Panaji');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (64,11,'Madgaon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (65,11,'Mormugao');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (66,12,'Ahmadabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (67,12,'Surat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (68,12,'Vadodara');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (69,12,'Rajkot');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (70,12,'Bhavnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (71,12,'Jamnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (72,12,'Junagadh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (73,12,'anand');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (74,12,'Navsari');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (75,12,'Surendranagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (76,12,'Morvi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (77,13,'Faridabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (78,13,'Gurgaon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (79,13,'Panipat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (80,13,'Yamunanagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (81,13,'Rohtak');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (82,13,'Hisar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (83,13,'Karnal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (84,13,'Sonipat');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (85,13,'Panchkula');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (86,13,'Ambala Sadar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (87,14,'Baddi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (88,14,'Chamba');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (89,15,'Srinagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (90,15,'Jammu');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (91,15,'Anantnag');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (92,15,'Udhampur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (93,15,'Baramula');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (94,15,'Sopore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (95,15,'Kathua');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (96,15,'Bandipura');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (97,15,'Leh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (98,16,'Jamshedpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (99,16,'Dhanbad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (100,16,'Ranchi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (101,16,'Bokaro Steel City');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (102,16,'Deoghar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (103,16,'Phusro');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (104,16,'Hazaribag');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (105,16,'Giridih');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (106,16,'Ramgarh Cantonment');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (107,16,'Medininagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (108,16,'Chirkunda');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (109,17,'Bengaluru');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (110,17,'Mysore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (111,17,'Hubli-Dharwar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (112,17,'Mangalore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (113,17,'Belgaum');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (114,17,'Gulbarga');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (115,17,'Davanagere');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (116,17,'Bellary');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (117,17,'Bijapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (118,17,'Shimoga');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (119,17,'Tumkur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (120,18,'Kochi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (121,18,'Kozhikode');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (122,18,'Thrissur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (123,18,'Malappuram');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (124,18,'Thiruvananthapuram');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (125,18,'Kannur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (126,18,'Kollam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (127,18,'Cherthala');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (128,18,'Kayamkulam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (129,18,'Kottayam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (130,19,'Amini');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (131,19,'Andrott');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (132,19,'Kavaratti');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (133,19,'Minicoy');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (134,20,'Indore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (135,20,'Bhopal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (136,20,'Jabalpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (137,20,'Gwalior');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (138,20,'Ujjain');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (139,20,'Sagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (140,20,'Dewas');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (141,20,'Satna');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (142,20,'Ratlam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (143,20,'Rewa');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (144,21,'Mumbai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (145,21,'Pune');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (146,21,'Nagpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (147,21,'Nashik');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (148,21,'Vasai-Virar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (149,21,'Aurangabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (150,21,'Solapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (151,21,'Bhiwandi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (152,21,'Amravati');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (153,22,'Imphal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (154,22,'Kakching');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (155,22,'Mayang Imphal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (156,22,'Thoubal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (157,22,'Ukhrul');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (158,23,'Jowai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (159,23,'Nongstoin');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (160,23,'Shillong');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (161,23,'Tura');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (162,23,'Williamnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (163,24,'aizawl');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (164,24,'Champhai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (165,24,'Kolosib');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (166,24,'Lawngtlai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (167,24,'Lunglei');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (168,24,'Saiha');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (169,24,'Serchhip');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (170,25,'Chumukedima');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (171,25,'Dimapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (172,25,'Kohima');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (173,25,'Mokokchung');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (174,25,'Mon');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (175,25,'Tuensang');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (176,25,'Wokha');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (177,26,'Bhubaneswar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (178,26,'Cuttack');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (179,26,'Raurkela');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (180,26,'Brahmapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (181,26,'Sambalpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (182,26,'Puri');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (183,26,'Baleshwar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (184,26,'Bhadrak');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (185,26,'Baripada');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (186,27,'Karaikal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (187,27,'Mahe');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (188,27,'Puducherry');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (189,27,'Yanam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (190,28,'Ludhiana');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (191,28,'Amritsar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (192,28,'Jalandhar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (193,28,'Patiala');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (194,28,'Bathinda');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (195,28,'S.A.S. Nagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (196,28,'Hoshiarpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (197,28,'Moga');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (198,28,'Pathankot');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (199,28,'Batala');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (200,29,'Jaipur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (201,29,'Jodhpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (202,29,'Kota');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (203,29,'Bikaner');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (204,29,'Ajmer');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (205,29,'Udaipur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (206,29,'Bhilwara');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (207,29,'Alwar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (208,29,'Bharatpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (209,30,'Gangtok');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (210,30,'Jorethang');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (211,30,'Namchi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (212,30,'Rangpo');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (213,31,'Chennai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (214,31,'Coimbatore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (215,31,'Madurai');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (216,31,'Tiruchirappalli');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (217,31,'Tiruppur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (218,31,'Salem');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (219,31,'Erode');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (220,31,'Tirunelveli');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (221,31,'Vellore');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (222,31,'Thoothukkudi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (223,32,'Hyderabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (224,32,'Warangal');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (225,32,'Nizamabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (226,32,'Karimnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (227,32,'Khammam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (228,32,'Ramagundam');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (229,32,'Mahbubnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (230,32,'Mancherial');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (231,32,'Nalgonda');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (232,32,'adilabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (233,33,'Agartala');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (234,33,'Belonia');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (235,33,'Bishalgarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (236,33,'Dharmanagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (237,33,'Kailashahar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (238,33,'Teliamura');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (239,33,'Udaipur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (240,34,'Kanpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (241,34,'Lucknow');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (242,34,'Ghaziabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (243,34,'agra');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (244,34,'Varanasi');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (245,34,'Meerut');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (246,34,'Allahabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (247,34,'Bareilly');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (248,34,'Aligarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (249,34,'Moradabad');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (250,35,'Dehra Dun');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (251,35,'Hardwar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (252,35,'Roorkee');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (253,35,'Haldwani');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (254,35,'Rudrapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (255,35,'Kashipur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (256,35,'Rishikesh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (257,35,'Pithoragarh');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (258,35,'Ramnagar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (259,35,'Kichha');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (260,35,'Manglaur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (261,35,'Jaspur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (262,36,'Kolkata');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (263,36,'asansol');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (264,36,'Shiliguri');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (265,36,'Durgapur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (266,36,'Bardhaman');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (267,36,'Ingraj Bazar');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (268,36,'Baharampur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (269,36,'Habra');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (270,36,'Kharagpur');
insert  into `city`(`city_id`,`state_id`,`city_name`) values (271,36,'Santipur');

/*Table structure for table `state` */

CREATE TABLE `state` (
  `state_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `state_name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`state_id`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8;

/*Data for the table `state` */

insert  into `state`(`state_id`,`state_name`) values (1,'Andaman & Nicobar Islands');
insert  into `state`(`state_id`,`state_name`) values (2,'Andhra Pradesh');
insert  into `state`(`state_id`,`state_name`) values (3,'Arunachal Pradesh');
insert  into `state`(`state_id`,`state_name`) values (4,'Assam');
insert  into `state`(`state_id`,`state_name`) values (5,'Bihar');
insert  into `state`(`state_id`,`state_name`) values (6,'Chandigarh');
insert  into `state`(`state_id`,`state_name`) values (7,'Chhatisgarh');
insert  into `state`(`state_id`,`state_name`) values (8,'Dadra & Nagar Haveli');
insert  into `state`(`state_id`,`state_name`) values (9,'Daman & Diu');
insert  into `state`(`state_id`,`state_name`) values (10,'Delhi');
insert  into `state`(`state_id`,`state_name`) values (11,'Goa');
insert  into `state`(`state_id`,`state_name`) values (12,'Gujarat');
insert  into `state`(`state_id`,`state_name`) values (13,'Haryana');
insert  into `state`(`state_id`,`state_name`) values (14,'Himachal Pradesh');
insert  into `state`(`state_id`,`state_name`) values (15,'Jammu & Kashmir');
insert  into `state`(`state_id`,`state_name`) values (16,'Jharkhand');
insert  into `state`(`state_id`,`state_name`) values (17,'Karnataka');
insert  into `state`(`state_id`,`state_name`) values (18,'Kerala');
insert  into `state`(`state_id`,`state_name`) values (19,'Lakshadweep');
insert  into `state`(`state_id`,`state_name`) values (20,'Madhya Pradesh');
insert  into `state`(`state_id`,`state_name`) values (21,'Maharashtra');
insert  into `state`(`state_id`,`state_name`) values (22,'Manipur');
insert  into `state`(`state_id`,`state_name`) values (23,'Meghalaya');
insert  into `state`(`state_id`,`state_name`) values (24,'Mizoram');
insert  into `state`(`state_id`,`state_name`) values (25,'Nagaland');
insert  into `state`(`state_id`,`state_name`) values (26,'Odisha');
insert  into `state`(`state_id`,`state_name`) values (27,'Puducherry');
insert  into `state`(`state_id`,`state_name`) values (28,'Punjab');
insert  into `state`(`state_id`,`state_name`) values (29,'Rajasthan');
insert  into `state`(`state_id`,`state_name`) values (30,'Sikkim');
insert  into `state`(`state_id`,`state_name`) values (31,'Tamil Nadu');
insert  into `state`(`state_id`,`state_name`) values (32,'Telangana');
insert  into `state`(`state_id`,`state_name`) values (33,'Tripura');
insert  into `state`(`state_id`,`state_name`) values (34,'Uttar Pradesh');
insert  into `state`(`state_id`,`state_name`) values (35,'Uttarakhand');
insert  into `state`(`state_id`,`state_name`) values (36,'West Bengal');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
